language: node_js
node_js: 14
cache: yarn
notifications:
  email: false
install:
  - yarn install
script:
  - yarn lint
  - yarn test
  - yarn code-dupe
  - yarn build
after_success:
  - codecov
  - yarn semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  keep-history: true
  github-token: '$GH_TOKEN'
  on:
    branch: master
